/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author edison
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    Color highlighted = new Color (230,230,230), neutral = new Color(240,240,240);
    private Connection cn;
    private PreparedStatement ps;
    private Statement st;
    private ResultSet rs;
        public void userPrimary(){
       
    try{
        Class.forName("com.mysql.jdbc.Driver"); 
        String getCurrentUserData = "Select * from cvarst.GRUsers where id= '" +  User.getUserID() + "'";
        cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
        st = cn.createStatement();
        rs = st.executeQuery(getCurrentUserData);
        while(rs.next()){
            nameLabel.setText(rs.getString("Name"));
       
          }
        }
        catch(Exception e){
            e.printStackTrace();
        }
     
       
//       System.out.print(userPrimary);
        
       
    }
    public HomeForm() {
        initComponents();
        setSize(1031, 602);
        setResizable(false);
        this.setBackground(new Color(255,255,255));
        grantRejectButton.setBackground(neutral);
        newUserPanel.setBackground(neutral);
        grantRejectButton.setHorizontalAlignment(SwingConstants.CENTER);
        addButton.setHorizontalAlignment(SwingConstants.CENTER);
        nameLabel.setHorizontalAlignment(SwingConstants.CENTER);
        logOutButton.setHorizontalAlignment(SwingConstants.CENTER);
        formTitle.setHorizontalAlignment(SwingConstants.CENTER);
        grantRejectPanel.setVisible(true);
        newUserPanel.setVisible(false);
        addIndicatorActive.setVisible(false);
        userPrimary();
        GRTable.getTableHeader().setDefaultRenderer(new HeaderColor());;
        GRTable.setBackground(new Color(255,255,255));
        
        String getData = "Select * from cvarst.GRTable";
           try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvarst?zeroDateTimeBehavior=convertToNull", "root", "");
            st = cn.createStatement();
            rs = st.executeQuery(getData);
            GRTable.setModel(DbUtils.resultSetToTableModel(rs));
            GRTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            

        }
           catch(Exception e){
           e.printStackTrace();}
           if(GRTable.getRowCount() == 0){
               controlCB.setEnabled(false);
           }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logOutButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        grantRejectButtonPanel = new javax.swing.JPanel();
        grantRejectIndicatorActive = new javax.swing.JLabel();
        grantRejectButton = new javax.swing.JLabel();
        addButtonPanel = new javax.swing.JPanel();
        addIndicatorActive = new javax.swing.JLabel();
        addButton = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        grantRejectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GRTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        controlCB = new javax.swing.JComboBox<>();
        addButton2 = new javax.swing.JButton();
        newUserPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        firstNameField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordVisibility = new javax.swing.JCheckBox();
        addButton1 = new javax.swing.JButton();
        minimizeButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        formTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(null);

        logOutButton.setBackground(new java.awt.Color(240, 240, 240));
        logOutButton.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        logOutButton.setForeground(java.awt.Color.gray);
        logOutButton.setText("Log out");
        logOutButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        logOutButton.setOpaque(true);
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logOutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logOutButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
        });
        jPanel1.add(logOutButton);
        logOutButton.setBounds(0, 220, 200, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home/profile_icon.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 40, 45, 40);

        nameLabel.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        nameLabel.setForeground(java.awt.Color.gray);
        nameLabel.setText("Chris Hemswo");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(0, 80, 200, 30);

        grantRejectButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grantRejectButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                grantRejectButtonPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grantRejectButtonPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grantRejectButtonPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grantRejectButtonPanelMouseEntered(evt);
            }
        });
        grantRejectButtonPanel.setLayout(null);

        grantRejectIndicatorActive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home/active_icon.png"))); // NOI18N
        grantRejectButtonPanel.add(grantRejectIndicatorActive);
        grantRejectIndicatorActive.setBounds(180, 0, 20, 40);

        grantRejectButton.setBackground(new java.awt.Color(240, 240, 240));
        grantRejectButton.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        grantRejectButton.setForeground(java.awt.Color.gray);
        grantRejectButton.setText("Grant/Reject");
        grantRejectButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        grantRejectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grantRejectButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                grantRejectButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grantRejectButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grantRejectButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grantRejectButtonMouseEntered(evt);
            }
        });
        grantRejectButtonPanel.add(grantRejectButton);
        grantRejectButton.setBounds(0, 0, 200, 40);

        jPanel1.add(grantRejectButtonPanel);
        grantRejectButtonPanel.setBounds(0, 140, 200, 40);

        addButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonPanelMouseEntered(evt);
            }
        });
        addButtonPanel.setLayout(null);

        addIndicatorActive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home/active_icon.png"))); // NOI18N
        addButtonPanel.add(addIndicatorActive);
        addIndicatorActive.setBounds(180, 0, 20, 40);

        addButton.setBackground(new java.awt.Color(240, 240, 240));
        addButton.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        addButton.setForeground(java.awt.Color.gray);
        addButton.setText("Add ");
        addButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
        });
        addButtonPanel.add(addButton);
        addButton.setBounds(0, 0, 200, 40);

        jPanel1.add(addButtonPanel);
        addButtonPanel.setBounds(0, 180, 200, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 200, 580);

        grantRejectPanel.setBackground(java.awt.Color.white);
        grantRejectPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                grantRejectPanelComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                grantRejectPanelComponentHidden(evt);
            }
        });
        grantRejectPanel.setLayout(null);

        jScrollPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jScrollPane1.setForeground(java.awt.Color.white);
        jScrollPane1.setOpaque(false);

        GRTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        GRTable.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        GRTable.setForeground(java.awt.Color.darkGray);
        GRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "Dr. Shane", "43", "Pending"},
                {"2", "2", "Dr. ALfred", "56", "Pending"},
                {"3", "4", "Dr. home", "43", "Granted"},
                {"4", "7", "Dr. Sebastiean", "23", "Rejected"}
            },
            new String [] {
                "ID", "Doctors ID", "Doctor Name", "Reload Request", "Status"
            }
        ));
        GRTable.setGridColor(java.awt.Color.white);
        GRTable.setOpaque(false);
        GRTable.setSelectionBackground(java.awt.Color.lightGray);
        GRTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GRTable);

        grantRejectPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 790, 310);

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel2.setText("Status");
        grantRejectPanel.add(jLabel2);
        jLabel2.setBounds(20, 340, 38, 30);

        controlCB.setBackground(java.awt.Color.white);
        controlCB.setFont(new java.awt.Font("Ubuntu Light", 0, 13)); // NOI18N
        controlCB.setMaximumRowCount(3);
        controlCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Granted", "Rejected", "Pending" }));
        grantRejectPanel.add(controlCB);
        controlCB.setBounds(70, 340, 160, 30);

        addButton2.setText("🔄");
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        grantRejectPanel.add(addButton2);
        addButton2.setBounds(750, 350, 60, 28);

        jLayeredPane1.add(grantRejectPanel);
        grantRejectPanel.setBounds(0, 0, 830, 580);

        newUserPanel.setBackground(java.awt.Color.white);
        newUserPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newUserPanelComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                newUserPanelComponentHidden(evt);
            }
        });
        newUserPanel.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel9.setForeground(java.awt.Color.gray);
        jLabel9.setText("New User");
        newUserPanel.add(jLabel9);
        jLabel9.setBounds(20, 20, 130, 24);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.gray);
        jLabel12.setText("Name");
        newUserPanel.add(jLabel12);
        jLabel12.setBounds(150, 100, 37, 16);

        firstNameField1.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N
        firstNameField1.setForeground(java.awt.Color.gray);
        newUserPanel.add(firstNameField1);
        firstNameField1.setBounds(220, 90, 510, 30);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.gray);
        jLabel19.setText("Username");
        newUserPanel.add(jLabel19);
        jLabel19.setBounds(130, 150, 64, 16);

        usernameField1.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N
        usernameField1.setForeground(java.awt.Color.gray);
        newUserPanel.add(usernameField1);
        usernameField1.setBounds(220, 140, 510, 30);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.gray);
        jLabel20.setText("Password");
        newUserPanel.add(jLabel20);
        jLabel20.setBounds(130, 200, 60, 16);

        passwordField.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N
        passwordField.setForeground(java.awt.Color.gray);
        passwordField.setEchoChar('\u2022');
        newUserPanel.add(passwordField);
        passwordField.setBounds(220, 190, 510, 30);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.gray);
        jLabel21.setText("Confirm Password");
        newUserPanel.add(jLabel21);
        jLabel21.setBounds(80, 250, 120, 16);

        confirmPasswordField.setFont(new java.awt.Font("Umpush", 0, 14)); // NOI18N
        confirmPasswordField.setForeground(java.awt.Color.gray);
        confirmPasswordField.setEchoChar('\u2022');
        newUserPanel.add(confirmPasswordField);
        confirmPasswordField.setBounds(220, 240, 510, 30);

        passwordVisibility.setForeground(java.awt.Color.gray);
        passwordVisibility.setText("show password");
        passwordVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordVisibilityActionPerformed(evt);
            }
        });
        newUserPanel.add(passwordVisibility);
        passwordVisibility.setBounds(220, 290, 131, 22);

        addButton1.setText("Add");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        newUserPanel.add(addButton1);
        addButton1.setBounds(620, 530, 170, 28);

        jLayeredPane1.add(newUserPanel);
        newUserPanel.setBounds(0, 0, 830, 580);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(200, 20, 830, 580);

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home/minimize_button.png"))); // NOI18N
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(minimizeButton);
        minimizeButton.setBounds(990, 0, 11, 20);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home/close_button.png"))); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(1010, 0, 11, 20);

        formTitle.setFont(new java.awt.Font("Ubuntu Condensed", 0, 13)); // NOI18N
        formTitle.setForeground(java.awt.Color.darkGray);
        formTitle.setText("Home");
        getContentPane().add(formTitle);
        formTitle.setBounds(0, 0, 1030, 20);

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setOpaque(true);
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1030, 20);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
           System.exit(0);
        
    }//GEN-LAST:event_closeButtonMouseClicked

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        // TODO add your handling code here:

        Point p = evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        // TODO add your handling code here:
        this.setState(HomeForm.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void passwordVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordVisibilityActionPerformed
        // TODO add your handling code here:
                if(passwordVisibility.isSelected()){
            System.out.print("showed");
            passwordField.setEchoChar((char)0);
            confirmPasswordField.setEchoChar((char)0);

        }
        else if(!passwordVisibility.isSelected()){
            passwordField.setEchoChar('•');
            confirmPasswordField.setEchoChar('•');
        }
    }//GEN-LAST:event_passwordVisibilityActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1ActionPerformed

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        // TODO add your handling code here:
        addButtonPanel.setBackground(highlighted);
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMousePressed
        // TODO add your handling code here:
         addButtonPanel.setBackground(neutral);
    }//GEN-LAST:event_addButtonMousePressed

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        // TODO add your handling code here:
         addButtonPanel.setBackground(neutral);
    }//GEN-LAST:event_addButtonMouseExited

    private void addButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseReleased
        // TODO add your handling code here:
        addButtonPanel.setBackground(highlighted);
    }//GEN-LAST:event_addButtonMouseReleased

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
       int confirmExitDialog = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
       if(confirmExitDialog == 0){
          LoginForm lf = new LoginForm();
          this.dispose();
          lf.setVisible(true);
       }
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setBackground(highlighted);
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setBackground(neutral);
    }//GEN-LAST:event_logOutButtonMouseExited

    private void logOutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMousePressed
        // TODO add your handling code here:
        logOutButton.setBackground(neutral);
    }//GEN-LAST:event_logOutButtonMousePressed

    private void logOutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseReleased
        // TODO add your handling code here:
                logOutButton.setBackground(highlighted);

    }//GEN-LAST:event_logOutButtonMouseReleased

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        newUserPanel.setVisible(true);
        grantRejectPanel.setVisible(false);
     
    }//GEN-LAST:event_addButtonMouseClicked

    private void addButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonPanelMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_addButtonPanelMouseEntered

    private void grantRejectButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonPanelMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_grantRejectButtonPanelMouseEntered

    private void grantRejectButtonPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonPanelMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_grantRejectButtonPanelMouseExited

    private void grantRejectButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonPanelMousePressed
        // TODO add your handling code here:
          // TODO add your handling code here:
      
    }//GEN-LAST:event_grantRejectButtonPanelMousePressed

    private void grantRejectButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonPanelMouseReleased
        // TODO add your handling code here:
          // TODO add your handling code here:
        
    }//GEN-LAST:event_grantRejectButtonPanelMouseReleased

    private void grantRejectButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonPanelMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_grantRejectButtonPanelMouseClicked

    private void grantRejectButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonMousePressed
        // TODO add your handling code here:
          grantRejectButtonPanel.setBackground(neutral);
    }//GEN-LAST:event_grantRejectButtonMousePressed

    private void grantRejectButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonMouseReleased
            grantRejectButtonPanel.setBackground(highlighted);
    }//GEN-LAST:event_grantRejectButtonMouseReleased

    private void grantRejectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonMouseClicked
        // TODO add your handling code here:
            grantRejectPanel.setVisible(true);
             newUserPanel.setVisible(false);
    }//GEN-LAST:event_grantRejectButtonMouseClicked

    private void grantRejectButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonMouseExited
        // TODO add your handling code here:
        grantRejectButtonPanel.setBackground(neutral);
    }//GEN-LAST:event_grantRejectButtonMouseExited

    private void grantRejectButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grantRejectButtonMouseEntered
        // TODO add your handling code here:
        grantRejectButtonPanel.setBackground(highlighted);
    }//GEN-LAST:event_grantRejectButtonMouseEntered

    private void newUserPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newUserPanelComponentShown
        // TODO add your handling code here:
        addIndicatorActive.setVisible(true);
    }//GEN-LAST:event_newUserPanelComponentShown

    private void newUserPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newUserPanelComponentHidden
        // TODO add your handling code here:
        addIndicatorActive.setVisible(false);
    }//GEN-LAST:event_newUserPanelComponentHidden

    private void grantRejectPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_grantRejectPanelComponentShown
        // TODO add your handling code here:
        grantRejectIndicatorActive.setVisible(true);
    }//GEN-LAST:event_grantRejectPanelComponentShown

    private void grantRejectPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_grantRejectPanelComponentHidden
        // TODO add your handling code here:
        grantRejectIndicatorActive.setVisible(false);
    }//GEN-LAST:event_grantRejectPanelComponentHidden

    private void GRTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRTableMouseClicked
        // TODO add your handling code here:
        if(GRTable.getSelectedRowCount() != 0){
        String status =(String) GRTable.getValueAt(GRTable.getSelectedRow(), 4);
        
            
            switch(status){
                case "Rejected":
                    controlCB.setSelectedIndex(1);
                case "Pending":
                   controlCB.setSelectedIndex(2);
                   break;
                case "Granted":
                    controlCB.setSelectedIndex(0);
                    break;
            
            }
        
          
        
        }
    }//GEN-LAST:event_GRTableMouseClicked

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        static public class HeaderColor extends DefaultTableCellRenderer{
        public HeaderColor(){
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable myTable, Object value, boolean selected, boolean focused,int row, int column){
            super.getTableCellRendererComponent(myTable, value, focused, focused, row, row);
            setBackground(new Color(255,255,255));
            setForeground(Color.DARK_GRAY);
            return this;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GRTable;
    private javax.swing.JLabel addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JPanel addButtonPanel;
    private javax.swing.JLabel addIndicatorActive;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JComboBox<String> controlCB;
    private javax.swing.JTextField firstNameField1;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel grantRejectButton;
    private javax.swing.JPanel grantRejectButtonPanel;
    private javax.swing.JLabel grantRejectIndicatorActive;
    private javax.swing.JPanel grantRejectPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOutButton;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox passwordVisibility;
    private javax.swing.JTextField usernameField1;
    // End of variables declaration//GEN-END:variables
}
